// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmFjtHNkuk4FsHl6-PVkVVi3UhdugW2RA',
    appId: '1:408468911096:web:f84c406519d0d64dcfdc0d',
    messagingSenderId: '408468911096',
    projectId: 'pi-natacao',
    authDomain: 'pi-natacao.firebaseapp.com',
    storageBucket: 'pi-natacao.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMvyb4JDREcFPozEkrd16sauvFeIRwDu0',
    appId: '1:408468911096:android:8ab76e751eddfdc6cfdc0d',
    messagingSenderId: '408468911096',
    projectId: 'pi-natacao',
    storageBucket: 'pi-natacao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Pnlwf7Yx_5qg9fwvt8RAsi7JrcqeO5c',
    appId: '1:408468911096:ios:87deb16e6bc196d3cfdc0d',
    messagingSenderId: '408468911096',
    projectId: 'pi-natacao',
    storageBucket: 'pi-natacao.appspot.com',
    iosBundleId: 'com.example.pinatacao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Pnlwf7Yx_5qg9fwvt8RAsi7JrcqeO5c',
    appId: '1:408468911096:ios:4b18a4479fe28de3cfdc0d',
    messagingSenderId: '408468911096',
    projectId: 'pi-natacao',
    storageBucket: 'pi-natacao.appspot.com',
    iosBundleId: 'com.example.pinatacao.RunnerTests',
  );
}
